name: Release Pack

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP archive
        working-directory: main
        run: |
          mkdir -p ../outputs
          zip -r ../outputs/JPP1.zip . -x "*.git/*"

      - name: Create or update GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: outputs/JPP.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: build-${{ github.run_number }}
          name: Build ${{ github.run_number }}
          prerelease: false
          allowUpdates: false
          replacesArtifacts: true